version: "3.9"
services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
